// <auto-generated />
namespace Simply_Gallery.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;

    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class Gallery : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Gallery));
        
        string IMigrationMetadata.Id
        {
            get { return "201812020104217_Gallery"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}