// <auto-generated />
namespace Simply_Gallery.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class Userimage : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Userimage));
        
        string IMigrationMetadata.Id
        {
            get { return "201811091911511_User image"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
