// <auto-generated />
namespace Simply_Gallery.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;

    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class UserImagemigration : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(UserImagemigration));
        
        string IMigrationMetadata.Id
        {
            get { return "201811081538489_UserImage-migration"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
